root: true
extends:
  - plugin:jest/recommended
  - plugin:jest/style
  - airbnb-typescript
  - airbnb-typescript/base
  - stylelint
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
  - plugin:unicorn/recommended
  - plugin:sonarjs/recommended
  - plugin:import/recommended
  - plugin:import/typescript
  - plugin:optimize-regex/recommended
  - prettier
  - plugin:prettier/recommended
plugins:
  - '@typescript-eslint'
  - unicorn
  - sonarjs
  - optimize-regex
  - react
  - jest
settings:
  react:
    version: 'detect'
  jest:
    version: 'detect'
  node:
    version: 'detect'
    tryExtensions:
      - '.js'
      - '.tsx'
      - '.json'
      - '.node'
      - '.ts'
      - '.d.ts'

env:
  browser: true
  jest/globals: true
  node: true

parser: '@typescript-eslint/parser'

parserOptions:
  ecmaVersion: 12
  ecmaFeatures:
    jsx: true
  project: './tsconfig.json'

overrides:
  - files:
      - '**/__tests__/**/*.[jt]s?(x)'
      - '**/?(*.)+(spec|test).[jt]s?(x)'
    extends:
      - plugin:jest/recommended
      - plugin:jest/style
      - plugin:jest-dom/recommended
      - plugin:testing-library/react
    plugins:
      - jest
      - jest-dom
      - testing-library
    rules:
      jest/no-disabled-tests: warn
      jest/no-focused-tests: error
      jest/no-identical-title: error
      jest/prefer-to-have-length: warn
      jest/valid-expect: error
      jest-dom/prefer-checked: error
      jest-dom/prefer-enabled-disabled: error
      jest-dom/prefer-required: error
      jest-dom/prefer-to-have-attribute: error
      testing-library/await-async-query: error
      testing-library/no-await-sync-query: error
      testing-library/no-debugging-utils: warn
      testing-library/no-dom-import: 'off'
    env:
      jest/globals: true

rules:
  no-shadow: off
  sort-imports: off
  react/prop-types: off
  react/react-in-jsx-scope: off
  arrow-body-style: error
  import/no-extraneous-dependencies: off
  import/prefer-default-export: off
  import/no-default-export: error
  import/no-anonymous-default-export: error
  import/extensions:
    - error
    - js: never
      jsx: never
      ts: never
      tsx: never
  '@typescript-eslint/no-unused-vars': off
  '@typescript-eslint/indent': off
  '@typescript-eslint/no-shadow': error
  '@typescript-eslint/no-floating-promises': off
  no-tabs: warn
  indent:
    - warn
    - 2
  no-restricted-syntax: off
  react/state-in-constructor: off
  unicorn/no-null: off
  react/require-default-props:
    - warn
    - ignoreFunctionalComponents: true
  unicorn/filename-case:
    - warn
    - cases:
        camelCase: true
        pascalCase: true
      ignore:
        - URL
        - API
  unicorn/prevent-abbreviations:
    - error
    - replacements:
        props:
          properties: false
  no-plusplus:
    - error
    - allowForLoopAfterthoughts: true
  react/jsx-filename-extension:
    - warn
    - extensions:
        - '.jsx'
        - '.tsx'
  sonarjs/prefer-immediate-return: warn
